name: flutter_todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  cupertino_icons: ^1.0.8
  path: ^1.9.1
  google_fonts: ^8.0.1
  flutter_signin_button: ^2.1.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  validatorless: ^1.2.5
  flutter_overlay_loader: ^2.0.0
  google_sign_in: ^7.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/todo-list.png

